baseURL = "https://test.cleaning-mammut.de"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Cleaning Mammut GmbH"
[markup.goldmark.renderer]
unsafe = true
